- name: create sudoer group file if it doesn't exist
  file:
    path: "/usr/local/etc/sudoers.d/wheel-group"
    state: touch

- name: "Allow admin users to sudo without a password"
  lineinfile:
    dest: "/usr/local/etc/sudoers.d/wheel-group" # path: in version 2.3
    state: "present"
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"

- name: add users
  user:
    name: "{{ item }}"
    comment: "User Account {{ item }}"
    groups: "wheel"
    shell: "/usr/local/bin/zsh"
  with_items: "{{ users }}"

- name: "Add authorized keys"
  authorized_key:
    user: "{{ item }}"
    key: "https://raw.githubusercontent.com/pertruccio/dotfiles/master/.ssh/authorized_keys"
  with_items: "{{ users }}"